### ISSUE TITLE
ADT Pulse July 25 changes appear to have broken the plugin

### ISSUE THREAD

**Issue by ibogost** [mrjackyliang/homebridge-adt-pulse#104]
### Describe the bug:
Overnight between July 24 and 25, the ADT Pulse plug-in cannot login to accounts or operate ADT system. Logging into ADT Pulse app today produces the following pop up message:

“Starting on 7/25, ADT is enhancing our security protocols for the Pulse app.
Users will be asked to log in and authenticate their devices (press yes if you recognize the device). If you have any questions, please visit our Support Center.“

I have attempted to reset 2FA but cannot determine if this will help. The fingerprint value did not change, and I have not yet tried creating a new ADT account. 

(The plug-in was flooding ADT’s service with failed logins and their portal has blocked my network (hopefully temporarily). Whatever else is going on, the plug-in should probably not infinitely attempt to login like this.)

### Steps to reproduce the bug:
1. Use the plugin after 7/24/2023

### Expected behavior:
Successful login to ADT Pulse service by the plugin. 

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh

[7/25/2023, 7:12:24 AM] [ADT Pulse] running on linux (x64)
[7/25/2023, 7:12:24 AM] [ADT Pulse] homebridge-adt-pulse v2.1.7
[7/25/2023, 7:12:24 AM] [ADT Pulse] node v16.15.1
[7/25/2023, 7:12:24 AM] [ADT Pulse] homebridge v1.4.1

```

### Logs related to this bug:

```sh

ADT Pulse: Login failed.
ADT Pulse: Logging in...
ADT Pulse: Response path -> undefined
ADT Pulse: Response path matches -> fa lse
ADT Pulse: Login failed.
ADT Pulse: Logging in..
ADT Pulse: Response path -> undefined
ADT Pulse: Response path matches -> fa lse
ADT Pulse: Login failed.
ADT Pulse: Logging in..
ADT Pulse: Response path -> undefined
ADT Pulse: Response path matches -> fa lse
ADT Pulse: Login failed.

```

**Comment by knedd** [comment]
Check the last characters of the fingerprint.  Mine did change.

From: ibogost ***@***.***>
Date: Tuesday, July 25, 2023 at 8:47 AM
To: mrjackyliang/homebridge-adt-pulse ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mrjackyliang/homebridge-adt-pulse] ADT Pulse Julu 25 changes appear to have broken the plugin (Issue #104)
Describe the bug:

Overnight between July 24 and 25, the ADT Pulse plug-in cannot login to accounts or operate ADT system. Logging into ADT Pulse app today produces the following pop up message:

“Starting on 7/25, ADT is enhancing our security protocols for the Pulse app.
Users will be asked to log in and authenticate their devices (press yes if you recognize the device). If you have any questions, please visit our Support Center.“

I have attempted to reset 2FA but cannot determine if this will help. The fingerprint value did not change, and I have not yet tried creating a new ADT account.

(The plug-in was flooding ADT’s service with failed logins and their portal has blocked my network (hopefully temporarily). Whatever else is going on, the plug-in should probably not infinitely attempt to login like this.)

Steps to reproduce the bug:

  1.  Use the plugin after 7/24/2023

Expected behavior:

Successful login to ADT Pulse service by the plugin.

Homebridge information:

Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

[7/25/2023, 7:12:24 AM] [ADT Pulse] running on linux (x64)

[7/25/2023, 7:12:24 AM] [ADT Pulse] homebridge-adt-pulse v2.1.7

[7/25/2023, 7:12:24 AM] [ADT Pulse] node v16.15.1

[7/25/2023, 7:12:24 AM] [ADT Pulse] homebridge v1.4.1

Logs related to this bug:

ADT Pulse: Login failed.

ADT Pulse: Logging in...

ADT Pulse: Response path -> undefined

ADT Pulse: Response path matches -> fa lse

ADT Pulse: Login failed.

ADT Pulse: Logging in..

ADT Pulse: Response path -> undefined

ADT Pulse: Response path matches -> fa lse

ADT Pulse: Login failed.

ADT Pulse: Logging in..

ADT Pulse: Response path -> undefined

ADT Pulse: Response path matches -> fa lse

ADT Pulse: Login failed.

**Comment by ibogost** [comment]
Interesting. I did a diff on the old and new fingerprints and they were identical. I will try creating a new ADT user account to see if that forces it to update.

**Comment by ibogost** [comment]
Okay, knedd's answer is right. Resetting MFA did eventually work, but I had to kick it a few times to get it to regenerate a fingerprint. Not sure why.

**Comment by ibogost** [comment]
ADT Pulse MFA fingerprints need to be reset after Pulse Portal changes on July 25, 2023.
