### ISSUE TITLE
Bridge has stopped working due to change in ADT Auth

### ISSUE THREAD

**Issue by chillblend151** [mrjackyliang/homebridge-adt-pulse#105]
### Describe the bug:
ADT Pulse has made a change to its Auth model it seems.  My Bridge stopped working after an update from ADT.  

### Steps to reproduce the bug:
1. In the logs in HOOBS I'm getting " ADT Pulse Bridge error ADT Pulse: Login failed."  I checked and my fingerprint hasn't changed nor has my actual password.  So something must have changed with ADT under the hood to where I can authenticate per the usual.

### Expected behavior:
Bridge runs as before and I am able to arm and disarm my control panel

### The Apple device you are using:
- Device: iPhone 11 Pro
- OS: iOS 16.6

### Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:

```sh
Adt Pulse BridgeADT Pulseinforunning on linux (arm64)
10:34:32 AMAdt Pulse BridgeADT Pulseinfohomebridge-adt-pulse v2.1.7
10:34:32 AMAdt Pulse BridgeADT Pulseinfonode v18.16.1
10:34:32 AMAdt Pulse BridgeADT Pulseinfohomebridge v1.6.1
```

### Logs related to this bug:
Attempt to locate the bug in the logs, then replace `SAMPLE TEXT` inside the grave accents:

```sh
10:43:10 AMAdt Pulse BridgeerrorADT Pulse: Login failed.
```

**Comment by knedd** [comment]
Check the last few characters in your fingerprint. Mine changed at the end. KevinSent via iPhoneOn Jul 25, 2023, at 13:49, chillblend151 ***@***.***> wrote:﻿
Describe the bug:
ADT Pulse has made a change to its Auth model it seems.  My Bridge stopped working after an update from ADT.
Steps to reproduce the bug:

In the logs in HOOBS I'm getting " ADT Pulse Bridge error ADT Pulse: Login failed."  I checked and my fingerprint hasn't changed nor has my actual password.  So something must have changed with ADT under the hood to where I can authenticate per the usual.

Expected behavior:
Bridge runs as before and I am able to arm and disarm my control panel
The Apple device you are using:

Device: iPhone 11 Pro
OS: iOS 16.6

Homebridge information:
Find these 4 lines in the beginning of the logs, then replace the text inside the grave accents:
Adt Pulse BridgeADT Pulseinforunning on linux (arm64)
10:34:32 AMAdt Pulse BridgeADT Pulseinfohomebridge-adt-pulse v2.1.7
10:34:32 AMAdt Pulse BridgeADT Pulseinfonode v18.16.1
10:34:32 AMAdt Pulse BridgeADT Pulseinfohomebridge v1.6.1
Logs related to this bug:
Attempt to locate the bug in the logs, then replace SAMPLE TEXT inside the grave accents:
10:43:10 AMAdt Pulse BridgeerrorADT Pulse: Login failed.

**Comment by chillblend151** [comment]
Ah, good catch!  The last few characters were off.  I should have been more through.  Thank you so much for your help!
