### ISSUE TITLE
auto pause and notification when fingerprint expires

### ISSUE THREAD

**Issue by mdombrowski13** [mrjackyliang/homebridge-adt-pulse#112]
### Is your feature request related to a problem? Please describe.
I was locked out of the ADT Pulse web portal and the HomeKit integration due to a fingerprint expiring causing me the inability to use a browser or the app to arm/disarm/monitor my ADT Pulse status.

### Describe the solution you'd like:
As a user I would like the plugin to not lock me out of using my ADT Pulse online tools in my home.  An auto pause feature after a predetermined number of failed login attemps of the plug would prevent a complete lockout from the portal in the network.  Additionally a notification via a "Fake Sensor" in apple HomeKit that a fingerprint has expired at a minimum would be great so the user would be able to know that an action is needed to update the finger print.  These 2 features would prevent a lock out and notify the user to update the fingerprint.

### Describe alternatives you've considered:
a way for the homebridge  plugin to automatically login to the web portal and update a user finger print periodically would be nice as well.

**Comment by mrjackyliang** [comment]
There's a lot of factors that come into this. Sometimes a failed login doesn't necessarily mean the fingerprint expired or if the credentials are incorrect.

That's why an auto-pause feature isn't a great idea. However, the plugin does have a 10 minute delay in case the plugin fails to login continuously.

This is dependent on whether or not it is able to detect the error message of incorrect credentials.

And as you know, this plugin is entirely based on reverse engineering the portal, so no official documentation exists.

**Comment by mrjackyliang** [comment]
> Maybe a new setting to specify how many failed logins to stop trying after and issue an error/notification?
> 
> 

I don't know if that works well. I know ADT Pulse will stop allowing you to login after 3 attempts, but those get triggered very randomly and may just cause more false positive
