### ISSUE TITLE
Let Me Choose Device and Zone Statuse Query Request Rates

### ISSUE THREAD

**Issue by NathanBlais** [mrjackyliang/homebridge-adt-pulse#42]
I would really like to be able to increase the pooling rate from 3 seconds. Over 60% of my web queries are going to portal.adtpulse.com. This is straining my poor old router and makes it harder for me to see other applications that use a lot of data with my Pi-hole.

Is there any way you can give me the option to change the pooling rate or is there a way we can keep the connection open?
Any way to reduce the number of portal.adtpulse.com queries would be ideal.

Thank you for your time

**Comment by mrjackyliang** [comment]
The reason why I set the pooling rate to 3 seconds is because of how the ADT Pulse normally polls on their site. I remember doing development on this plugin and set it to a longer polling rate but that caused Siri to respond with "device not responding" errors. It's not the best solution at the moment because the plugin isn't running on an official API but is scraping the website to retrieve those details.
